title: About Me
author: Shrey Karmacharya
email: shreykarmacharya@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Please Click Now Or Else...

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: DistinctDev3465 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
